### ISSUE TITLE
why always failed to run due to "Option:unwrap()' on a 'None' value

### ISSUE THREAD

**Issue by ljsheng7128** [slint-ui/slint-rust-template#12]
alli3@delnorta-ubuntu:~/test/slint-rust-template$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

alli3@delnorta-ubuntu:~/test/slint-rust-template$ rustc -V
rustc 1.66.0 (69f9c33d7 2022-12-12)

alli3@delnorta-ubuntu:~/test/slint-rust-template$ RUST_BACKTRACE='full' cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/slint-rust-template`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_consumer-0.15.0/src/tree.rs:274:45
stack backtrace:
   0:     0x561529679ff0 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561529679ff0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561529679ff0 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x561529679ff0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5615296a0cee - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x561529673775 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x561529679db5 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x561529679db5 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x56152967b66f - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x56152967b3aa - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x56152967bd68 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x56152967bac1 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:     0x56152967a49c - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x56152967b822 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x5615282297e3 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x5615282298bd - core::panicking::panic::h9ced3cf2f605ba6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
  16:     0x5615284f163d - core::option::Option<T>::unwrap::hf182507854416e37
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:778:21
  17:     0x5615284f4977 - accesskit_consumer::tree::Tree::new::hd99b71c236c87566
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_consumer-0.15.0/src/tree.rs:274:19
  18:     0x56152837e8f9 - accesskit_unix::adapter::Adapter::new::hc9f31dd63da13d35
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_unix-0.5.0/src/adapter.rs:53:20
  19:     0x561528365a5d - accesskit_winit::platform_impl::platform::Adapter::new::ha1aa84b1e2aadf3a
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_winit-0.14.1/src/platform_impl/unix.rs:21:23
  20:     0x56152832d3a7 - accesskit_winit::Adapter::with_action_handler::h6610612c36278bf9
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/accesskit_winit-0.14.1/src/lib.rs:170:23
  21:     0x561528335d57 - i_slint_backend_winit::accesskit::AccessKitAdapter::new::h70a5f3e8bced78b0
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-winit-1.1.0/accesskit.rs:62:20
  22:     0x5615283b1394 - i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter::new::{{closure}}::h0b0754e752374deb
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-winit-1.1.0/winitwindowadapter.rs:162:32
  23:     0x56152833edbc - alloc::rc::Rc<T>::new_cyclic::hfeb409d1af52e4ac
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/rc.rs:454:20
  24:     0x5615283b0c32 - i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter::new::h94f76373cf88032c
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-winit-1.1.0/winitwindowadapter.rs:147:23
  25:     0x56152833b99d - i_slint_backend_winit::window_factory_fn::hdd562811ba943473
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-winit-1.1.0/lib.rs:71:5
  26:     0x56152833bdb9 - <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::create_window_adapter::h7721a6e16abca307
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-winit-1.1.0/lib.rs:214:9
  27:     0x56152829e9c9 - slint::private_unstable_api::create_window_adapter::{{closure}}::hd8f771a197a888c7
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/slint-1.1.0/private_unstable_api.rs:151:49
  28:     0x56152829f09c - i_slint_core::with_platform::{{closure}}::h3fac298cac5922d0
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.1.0/lib.rs:98:20
  29:     0x56152829fc32 - std::thread::local::LocalKey<T>::try_with::hcc39143592ab0f8c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/local.rs:446:16
  30:     0x56152829fa9e - std::thread::local::LocalKey<T>::with::h46ca1fbfdb12efdf
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/local.rs:422:9
  31:     0x56152829ebd9 - i_slint_core::with_platform::hd3869af0adcf8e64
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.1.0/lib.rs:97:5
  32:     0x56152829eb02 - i_slint_backend_selector::with_platform::hac62727c518d4918
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-selector-1.1.0/lib.rs:82:5
  33:     0x56152829e99e - slint::private_unstable_api::create_window_adapter::h62d622b518201cf8
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/slint-1.1.0/private_unstable_api.rs:151:5
  34:     0x56152824966c - slint_rust_template::slint_generatedAppWindow::InnerAppWindow::window_adapter_ref::{{closure}}::h0a158b8e11189e28
                               at /home/alli3/test/slint-rust-template/target/debug/build/slint-rust-template-ef21a42e9098fa40/out/appwindow.rs:2172:32
  35:     0x56152827b4ac - once_cell::unsync::OnceCell<T>::get_or_try_init::h9807ef9712c0907c
                               at /home/alli3/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.18.0/src/lib.rs:631:23
  36:     0x561528259f7c - slint_rust_template::slint_generatedAppWindow::InnerAppWindow::window_adapter_ref::h5afe3f5f7f506824
                               at /home/alli3/test/slint-rust-template/target/debug/build/slint-rust-template-ef21a42e9098fa40/out/appwindow.rs:2171:14
  37:     0x56152825ae3f - <slint_rust_template::slint_generatedAppWindow::AppWindow as i_slint_core::api::ComponentHandle>::show::hf1b9b1017de14595
                               at /home/alli3/test/slint-rust-template/target/debug/build/slint-rust-template-ef21a42e9098fa40/out/appwindow.rs:2273:14
  38:     0x56152825ab87 - <slint_rust_template::slint_generatedAppWindow::AppWindow as i_slint_core::api::ComponentHandle>::run::hcc142652c431e1e3
                               at /home/alli3/test/slint-rust-template/target/debug/build/slint-rust-template-ef21a42e9098fa40/out/appwindow.rs:2268:14
  39:     0x56152823a685 - slint_rust_template::main::hbed4839128582a5a
                               at /home/alli3/test/slint-rust-template/src/main.rs:12:5
  40:     0x56152822fc62 - core::ops::function::FnOnce::call_once::h103db99dfecf4358
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  41:     0x561528279f05 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd210306e893db401
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  42:     0x56152827fa36 - std::rt::lang_start::{{closure}}::h4c468e464aaf2ca5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:166:18
  43:     0x56152966f0cb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h072eb4cd8da964ba
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286:13
  44:     0x56152966f0cb - std::panicking::try::do_call::h8eca204fe9266946
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  45:     0x56152966f0cb - std::panicking::try::h12574e1b7b2cbacb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  46:     0x56152966f0cb - std::panic::catch_unwind::hf71522d4448329d6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  47:     0x56152966f0cb - std::rt::lang_start_internal::{{closure}}::h65b66ac9bff580f8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:48
  48:     0x56152966f0cb - std::panicking::try::do_call::hfff61e33ca3db9f1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  49:     0x56152966f0cb - std::panicking::try::he48c8ecead279cad
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  50:     0x56152966f0cb - std::panic::catch_unwind::hd510a26bfc950ccc
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  51:     0x56152966f0cb - std::rt::lang_start_internal::hc680b25eab888da9
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:20
  52:     0x56152827fa0a - std::rt::lang_start::h92a287ee1731e41e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:165:17
  53:     0x56152823a6ce - main
  54:     0x7fbdf0a99083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  55:     0x561528229c8e - _start
  56:                0x0 - <unknown>

**Comment by ogoffart** [comment]
Thanks for reporting a bug.

This is this problem: https://github.com/slint-ui/slint/issues/3055

Workarounds: either of

1. disable the accessibility features (that is enabled by default)
2. downgrade the zbus crate with this command: `cargo update -p zbus --precise 3.10.0`  (or pin it to that version in the Cargo.toml)
