### ISSUE TITLE
I got an error when I initialized cargo build on macos 14.3

### ISSUE THREAD

**Issue by dannysun85** [slint-ui/slint-rust-template#15]
I initialized and created the program and running cargo build directly got the following error:

![image](https://github.com/slint-ui/slint-rust-template/assets/16036106/35b174e1-8451-4d14-a452-d77a379811a0)

The final error will look like this:

![image](https://github.com/slint-ui/slint-rust-template/assets/16036106/d37a448b-d6f3-4e2a-b60f-1b08d838db57)

I don't know where the problem is, I have searched many places but can't find the cause of the error.

**Comment by tronical** [comment]
Somehow you seem to have Qt installed on your Mac. What version of Slint are you using? 

If you're looking for a workaround, I suggest to either remove `qmake` from your `PATH` or set `SLINT_NO_QT=1`.

**Comment by dannysun85** [comment]
I really don't know why QTkit was installed, set SLINT_NO_QT=1 and everything worked fine. This problem has been bothering me for a long time, thank you so much it has been solved.

**Comment by tronical** [comment]
Would you still be able to paste us the output of `which qmake` and `qmake -query`? The `SLINT_NO_QT=1` is just a workaround, we'd like to get to the root cause :)

**Comment by dannysun85** [comment]
So far it looks like it's my anaconda3 installation. They will install qtkit automatically.

<img width="318" alt="image" src="https://github.com/slint-ui/slint-rust-template/assets/16036106/61307912-328d-4b0a-8c9d-56b1cc9f17c2">

<img width="480" alt="image" src="https://github.com/slint-ui/slint-rust-template/assets/16036106/cf8cd269-ad93-455f-9412-6040a5b9ce56">

**Comment by tronical** [comment]
Thank you for the info! That explains it. That might make it possible for us to reproduce it. Is this a bare-bones anaconda 3 install or did you install anything inside?

**Comment by dannysun85** [comment]
Indeed, this problem is also something we all need to pay attention to. At present, the best solution is to automatically set the configuration file for the user when installing. anaconda3 is the installation package I downloaded from the official.dmg, and installed directly.

**Comment by ogoffart** [comment]
Similar as https://github.com/slint-ui/slint/issues/4560
Fixed by https://github.com/slint-ui/slint/pull/4566 which disable Qt on mac by default even if it is found.

**Comment by dannysun85** [comment]
This is an exciting fix that helps us solve a lot of big problems!
