### ISSUE TITLE
command to generate the template does not recognize git repo

### ISSUE THREAD

**Issue by asunny72** [slint-ui/slint-rust-template#19]
README advises to set up a sample project via the command  `cargo generate --git https://github.com/slint-ui/slint-rust-template --name my-project`

This command does not work. I see the error:

```
Error: Please check if the Git user / repository exists.

Caused by:
    could not read from remote repository; class=Net (12); code=Eof (-20)
```

**Comment by tronical** [comment]
The command works for me:

```
cargo generate --git https://github.com/slint-ui/slint-rust-template --name my-project
🔧   Destination: /Users/simon/src/tmp/my-project ...
🔧   project-name: my-project ...
🔧   Generating template ...
🔧   Moving generated files into: `/Users/simon/src/tmp/my-project`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/simon/src/tmp/my-project
```

Is it possible that there is a problem with your git or network installation?

Could you try running this? `git clone https://github.com/slint-ui/slint-rust-template`  (you can delete the resulting directory afterwards)

**Comment by asunny72** [comment]
I can successfully git clone (and verified resulting directories exist):

```
Cloning into 'slint-rust-template'...
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 96 (delta 19), reused 15 (delta 15), pack-reused 62
Receiving objects: 100% (96/96), 14.95 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (43/43), done.
```

Yet, I see the same error as my original inquiry when I try the cargo generate command.

The only easy-to-think-of differences with our git set up is that I'm not a member of the slint team. Could that be an issue?

Also, which cargo generate version do you have? I'm using `cargo-generate v0.21.2`.

**Comment by tronical** [comment]
That's odd, I'm using the same version of `cargo-generate` (on macOS).

> The only easy-to-think-of differences with our git set up is that I'm not a member of the slint team. Could that be an issue?

Since you can git clone the same repo, I don't think that's the issue. My best guess at this point is that while git on the command line works, cargo-generate uses libgit2 and somehow that one doesn't work.

If all else fails, you could try `cargo generate --git /path/to/your/manually/cloned/slint-rust-template --name my-project`

**Comment by ogoffart** [comment]
This seems like a bug in cargo-generate. Could you perhaps fill a bug in the upstream project? https://github.com/cargo-generate/cargo-generate?
I don't think there is anything we can do in this repo or in Slint to solve this issue.

**Comment by ogoffart** [comment]
Closing this issue in this repository since I don't think this is a bug on our side.

**Comment by cbrevik** [comment]
For posterity, I had the following in my global `.gitconfig`:
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

If I commented it out while running the `cargo generate`-command it worked for me. It's not a fix, obviously, but it'll get you unstuck.
