### ISSUE TITLE
wrong documentation

### ISSUE THREAD

**Issue by Frank-Buss** [slint-ui/slint-rust-template#4]
`cargo generate --git slint-ui/slint-rust-template --name my-project` result in this error, with the latest stable Rust version:
```
Error: Please check if the Git user / repository exists.

Caused by:
    unsupported URL protocol; class=Net (12)
```
The right command was `cargo generate --git https://github.com/slint-ui/slint-rust-template --name my-project`.

**Comment by ogoffart** [comment]
Thanks for the bug report.
